<?php
namespace App\Constants;

// Range 1000-1999 Should be error code generated by client
// Range 1400-1499 Used by 4xx status code
// Range 2000-2999 Should be error code generated by server
// Range 2500-2599 Used by 5xx status code
// Range 3000-3999 Should be error code generated by third party API
final class ErrorCodes
{
    public const UNAUTHORIZED_BY_CORS = 1001;
    public const UNAUTHORIZED_BY_JWT = 1002;

    private function __construct() { }
}